### ISSUE TITLE
Support multiple collections

### ISSUE THREAD

**Issue by xplosionmind** [shorty25h0r7/jekyll-wikilinks#4]
As mentioned in “[future features](https://github.com/shorty25h0r7/jekyll-wikilinks#future-features "Future Features in README")”.

example of multiple collections specifications in `_config.yml`:

```yaml
wikilinks:
  collections:
    - '_notes'
    - '_pages'
```
