### ISSUE TITLE
Remove permalink and title requirement

### ISSUE THREAD

**Issue by xplosionmind** [shorty25h0r7/jekyll-wikilinks#6]
As of right now, in every single note it is required to specify in the front matter both a `permalink` and a `title`.  
Nevertheless, it is definitely not convenient. Since I have title and permalink patterns defined in `_config.yml`, it would be crucial for the plugin to generate them based on front matter defaults if nothing is specified in front matter.

**Comment by shorty25h0r7** [comment]
Could you do me a favor and show me the related configs in `_config.yml` you're using?

**Comment by xplosionmind** [comment]
My [`_config.yml`](https://github.com/xplosionmind/tommi.space/blob/main/_config.yml 'tommi.space’s config file'):

```yaml
title: Tommi Space
email: surfing@tommi.space
description: >-
  A virtual representation of the mess inside Tommi’s mind
baseurl: ""
url: "https://tommi.space"
author:
  name: Tommi
  username: tommi
  picture: "/images/profile.jpg"
logo: "/favicon.ico"
publisher: Tommi
timezone: Europe/Rome
github_username: xplosionmind
git_repository: "tommi.space"
future: true
profile: true
livereload: true
strict_front_matter: true
lang: it
locale: it
images: "/images"
post-images: "/images/posts"
image: '/logos/favicon-180.png'
assets: "https://assets.tommi.space/assets"
video: "https://assets.tommi.space/video"
audio: "https://assets.tommi.space/audio"
logos: "/logos"
fonts: "/fonts"
exclude:
  - riordinare/
  - _notes/private/
  - _notes/templates/
  - _notes/.obsidian
  - _notes/.trash
  - _notes/PISE
  - _notes/university
  - _notes/obsidian.css
  - _data/private
  - _notes/.*
  - _data/.*
keep_files:
  - images/
  - assets/
collections:
  poetry:
    output: true
  notes:
    output: true
  filinge:
    output: true
  sconnesso:
    output: true

# CommonMark
# markdown: CommonMark
# commonmark:
#  options: ["FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE", "SMART", "VALIDATE_UTF8", "UNSAFE", "LIBERAL_HTML_TAG", "HARDBREAKS"]
#  extensions: ["strikethrough", "table", "tasklist", "autolink", "tagfilter"]

# Pagination
pagination:
  enabled: true
  sort_reverse: true
  per_page: 5
  title: ':title :num'
  trail: 
    before: 2
    after: 2

feed:
  path: /feeds/zibaldone.xml
  tags:
    path: /feeds/
    only:
      - geek
  collections:
    poetry:
      path: /feeds/poetry.xml
    filinge:
      path: /feeds/filinge.xml
    notes:
      path: /feeds/jam.xml

# SEO
social:
  name: xplosionmind
tagline: "Tommi’s virtual mind"
twitter:
  username: xplosionmind
  card: summary

toc:
  list_class: "grey border box"

podcast:
  title: Sconnesso
  description: "Sconnesso è uno pseudo-podcast in cui, per alcuni minuti, racconto ciò che mi sorprende. Sconnesso è sbagliato, ma non scorretto. È atipico, ma non è poi così originale. È curato, ma non studiato alla perfezione. È esasperante, ma mai noioso. È improvvisato, ma non raffazzonato. Non è preparato, ma è attentamente pensato. È confuso e disordinato, ma non complicato. È sconnesso, ma non disconnesso."
  url: "/sconnesso.xml"
  author: "Tommi"
  email: "sono@sconnesso.link"
  link: "https://sconnesso.link"
  logo: "/images/sconnesso.jpg"
  type: "episodic"
  complete: "yes"
  block: "no"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-redirect-from
  - jekyll-datapage-generator
  - jekyll-debug
  - jekyll-mentions
  - jekyll-liquify
  - jekyll-auto-image
  - jekyll-email-protect
  - jekyll-toc
  - jekyll-paginate-v2
#  - jekyll-stork
#  - jekyll-webmention_io
#  - jekyll-lunr
#  - jekyll-wikilinks

sass:
  style: compressed

target-blank:
  rel: external

# wikilinks_collection: "notes"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: all

permalink: /:title

defaults:
  -
    scope:
      path: ""
    values:
      layout: "wrapper"
      lang: "en"
      image: "/images/preview.gif"
      comments: true
      serif: false
      primary: "#FCC920"

  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: it
      excerpt_separator: "<!--more-->"

  -
    scope:
      path: ""
      type: poetry
    values:
      layout: poetry
      lang: it
      permalink: /:title
      primary: "teal"
      description: "Parole disordinate, fra le nuvole e lo spazio"

  -
    scope:
      path: ""
      type: notes
    values:
      layout: jam
      lang: en
      toc: true
      permalink: /:title
      hide: 0

  -
    scope:
      path: ""
      type: sconnesso
    values:
      layout: sconnesso
      lang: it
      permalink: /sconnesso/:title
      primary: "var(--purple)"
      author: "Tommi"
      categories: "sconnesso"
      episodeType: "full"
      explicit: "no"
      image: "/images/sconnesso.jpg"

  -
    scope:
      path: ""
      type: filinge
    values:
      layout: post
      lang: it
      primary: "#20CE88"
      permalink: /filinge/:title
```
